# server
server:
  servlet:
    context-path: /psychology
  port: 8089

#spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mysql://192.1168.123.188:3306/psychology?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cdu.psychology.entity
  configuration:
    map-underscore-to-camel-case: true

#showSql
#logging:
#  level:
#    com:
#      cdu:
#        psychology:
#          dao: DEBUG